<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <MyType>Empty</MyType>
    <RootNamespace>MonkMode</RootNamespace>
    <AssemblyName>monkmode</AssemblyName>
    <StartupObject>MonkMode.Program</StartupObject>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationManifest>My Project\app.manifest</ApplicationManifest>
    <ApplicationIcon>monkmode_icon.ico</ApplicationIcon>
    <OptionExplicit>On</OptionExplicit>
    <OptionStrict>Off</OptionStrict>
    <OptionInfer>On</OptionInfer>
    <OptionCompare>Binary</OptionCompare>
    <NoWarn>42016,41999,42017,42018,42019,42032,42036,42020,42021,42022</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System" />
    <Import Include="System.Collections.Generic" />
    <Import Include="System.Diagnostics" />
  </ItemGroup>

</Project>
